title: Hello, world! I'm Dao Vo
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/daovo.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Dao Vo # add your name
author-img: daovo.jpg # add your photo
about-author: Collaborating with leaders to solve their customer's most challenging problems on Azure. # add description
social-twitter: votrongdao# add your Twitter handle
social-facebook: votrongdao# add your Facebook handle
social-github: daovo # add your Github handle
social-linkedin: votrongdao # add your Linkedin handle
social-email: votrongdao@gmail.com # add your Email address

# Disqus
discus-identifier: DaoVo # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
